(defproject puzzles "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.6.0"]]
  :sub [ "accumulate"
         "allergies"
         "anagram"
         "atbash-cipher"
         "bank-account"
         "beer-song"
         "binary"
         "binary-search-tree"
         "bob"
         ;; "crypto-square"
         "difference-of-squares"
         "etl"
         "gigasecond"
         "grade-school"
         "grains"
         "hexadecimal"
         "kindergarten-garden"
         "largest-series-product"
         "leap"
         "meetup"
         "nucleotide-count"
         "phone-number"
         "point-mutations"
         "prime-factors"
         "queen-attack"
         "raindrops"
         "rna-transcription"
         "robot-name"
         "robot-simulator"
         "roman-numerals"
         "scrabble-score"
         "space-age"
         "triangle"
         "word-count" ])
